export const fieldUnits: Record<string, string> = {
  screwJD: 'kN',
  nailDiameter: 'mm',
  designLoad: 'kN',
  screwPenetration: 'mm',
  firstTimberThickness: 'mm',
  timberThickness: 'mm',
  boltSize: 'mm',
  qsk: 'kN',
  designStrength: 'kN',
  soilDensity: 'kN/m3',
  pileHeight: 'mm',
  pileDiameter: 'mm',
  frictionResistanceAS: 'kN',
  frictionResistanceMH: 'kN',
  weight: 'kN',
  cohension: 'kPa',
  endBearing: 'kN',
  totalUpliftResistance: 'kN',
  totalPileCapacityAS: 'kN',
  totalPileCapacityMH: 'kN',
  lp: 'mm',
  qk: 'N/mm'
}
