export const fieldUnits: Record<string, string> = {
  screwJD: 'KN',
  nailDiameter: 'mm',
  designLoad: 'KN',
  screwPenetration: 'mm',
  firstTimberThickness: 'mm',
  timberThickness: 'mm',
  boltSize: 'mm',
  qsk: 'KN',
  designStrength: 'KN',
  soilDensity: 'Kn/m3',
  pileHeight: 'mm',
  pileDiameter: 'mm',
  frictionResistanceAS: 'KN',
  frictionResistanceMH: 'KN',
  weight: 'KN',
  cohension: 'Kpa',
  endBearing: 'KN',
  totalUpliftResistance: 'KN',
  totalPileCapacityAS: 'KN',
  totalPileCapacityMH: 'KN',
  lp: 'mm',
  qk: 'N/mm'
}
